/**
 * v0.19.0 gap-closures (from the 2026-07-21 landscape re-survey):
 *  - in-toto/DSSE attestation emitted next to signed sync manifests, with the
 *    honest posture (standard predicate + SSHSIG, not a Sigstore bundle),
 *    verified end to end including subject/manifest divergence and signer
 *    authentication.
 *  - AGENTS.md as a first-class IMPORT input: root and nested files
 *    discovered (the spec's monorepo pattern), vendored trees skipped.
 */

import { describe, it, expect } from "vitest";
import { execSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import {
  dssePae,
  buildInTotoStatement,
  buildDsseEnvelope,
  verifyAttestationFile,
  computeManifestDigest,
  INTOTO_PAYLOAD_TYPE,
} from "../scripts/lib/provenance.js";
import { scanRepoDirs } from "../scripts/lib/import.js";

const ROOT = path.resolve(__dirname, "..");
const TSX = path.join(ROOT, "node_modules", ".bin", "tsx");

function run(script: string): string {
  return execSync(`${TSX} ${script}`, {
    cwd: ROOT, env: { ...process.env, NODE_NO_WARNINGS: "1" }, timeout: 120_000,
  }).toString();
}

const sshAvailable = (() => {
  try {
    const r = spawnSync("ssh-keygen", ["-Y", "sign", "-h"], { stdio: "pipe", timeout: 10_000 });
    return r.status !== 127 && r.error === undefined;
  } catch { return false; }
})();

describe("DSSE PAE", () => {
  it("encodes per spec: DSSEv1 SP len(type) SP type SP len(body) SP body", () => {
    const pae = dssePae("application/example", Buffer.from("hello"));
    expect(pae.toString("utf-8")).toBe("DSSEv1 19 application/example 5 hello");
  });
});

describe("in-toto statement", () => {
  it("subjects = every manifest file digest + the manifest digest itself", () => {
    const manifest: Record<string, unknown> = {
      files: [
        { path: ".claude/a.md", hash: "a".repeat(64) },
        { path: ".claude/b.sh", hash: "b".repeat(64) },
      ],
      provenance: { agentboot_version: "0.0.0" },
      scope: { group: null, team: null },
      synced_at: "2026-01-01T00:00:00Z",
    };
    manifest["integrity"] = { algorithm: "sha256", manifest_digest: computeManifestDigest(manifest) };
    const st = buildInTotoStatement(manifest);
    expect(st._type).toBe("https://in-toto.io/Statement/v1");
    expect(st.subject).toHaveLength(3);
    expect(st.subject.map((s) => s.name)).toContain(".agentboot-manifest.json");
    expect(st.predicate.provenance).toEqual({ agentboot_version: "0.0.0" });
  });
});

describe.skipIf(!sshAvailable)("attestation end to end", () => {
  function mkSignedHubSync(emitInToto: boolean): { hub: string; spoke: string; keyPath: string } {
    const hub = fs.mkdtempSync(path.join(os.tmpdir(), "ab-att-hub-"));
    const spoke = fs.mkdtempSync(path.join(os.tmpdir(), "ab-att-spoke-"));
    const keyPath = path.join(hub, "signing-key");
    execSync(`ssh-keygen -q -t ed25519 -N "" -f "${keyPath}"`, { timeout: 15_000 });
    fs.mkdirSync(path.join(hub, "core", "instructions"), { recursive: true });
    fs.writeFileSync(path.join(hub, "agentboot.config.json"), JSON.stringify({
      org: "acme",
      personas: { enabled: [], outputFormats: ["claude"] },
      traits: { enabled: [] },
      sync: { signing: { enabled: true, sshKeyPath: "./signing-key", emitInToto } },
      validation: { secretPatterns: [] },
    }));
    fs.writeFileSync(path.join(hub, "repos.json"), JSON.stringify([
      { path: spoke, platform: "claude" },
    ]));
    run(`scripts/compile.ts --config ${path.join(hub, "agentboot.config.json")}`);
    run(`scripts/sync.ts --config ${path.join(hub, "agentboot.config.json")} --adopt-existing`);
    return { hub, spoke, keyPath };
  }

  it("sync emits a verifiable attestation; tampering a synced file breaks subject match; payload tamper breaks the signature", () => {
    const { hub, spoke, keyPath } = mkSignedHubSync(true);
    try {
      const manifestPath = path.join(spoke, ".claude", ".agentboot-manifest.json");
      const attPath = path.join(spoke, ".claude", ".agentboot-manifest.intoto.json");
      expect(fs.existsSync(attPath)).toBe(true);

      // Signer authentication against the hub key.
      const pub = fs.readFileSync(keyPath + ".pub", "utf-8").trim().split(" ").slice(0, 2).join(" ");
      const allowed = path.join(hub, "allowed_signers");
      fs.writeFileSync(allowed, `ci@example.com ${pub}\n`);

      const ok = verifyAttestationFile(attPath, manifestPath, { allowedSignersPath: allowed });
      expect(ok.statementOk).toBe(true);
      expect(ok.subjectsMatchManifest).toBe(true);
      expect(ok.signatureOk).toBe(true);
      expect(ok.signerVerified).toBe(true);
      expect(ok.posture ?? "n/a").toBeDefined();

      // Manifest regenerated by an attacker (files changed + digest recomputed)
      // → the attestation's subjects no longer match.
      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
      manifest.files[0].hash = "0".repeat(64);
      manifest.integrity.manifest_digest = computeManifestDigest(manifest);
      fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
      const diverged = verifyAttestationFile(attPath, manifestPath, {});
      expect(diverged.subjectsMatchManifest).toBe(false);

      // Payload tampering breaks the SSHSIG over the PAE.
      const env = JSON.parse(fs.readFileSync(attPath, "utf-8"));
      const st = JSON.parse(Buffer.from(env.payload, "base64").toString("utf-8"));
      st.predicate.provenance.agentboot_version = "9.9.9";
      env.payload = Buffer.from(JSON.stringify(st), "utf-8").toString("base64");
      fs.writeFileSync(attPath, JSON.stringify(env, null, 2));
      const tampered = verifyAttestationFile(attPath, null, {});
      expect(tampered.signatureOk).toBe(false);
    } finally {
      fs.rmSync(hub, { recursive: true, force: true });
      fs.rmSync(spoke, { recursive: true, force: true });
    }
  });

  it("no attestation is emitted unless emitInToto is configured", () => {
    const { hub, spoke } = mkSignedHubSync(false);
    try {
      expect(fs.existsSync(path.join(spoke, ".claude", ".agentboot-manifest.intoto.json"))).toBe(false);
      // And the signed manifest itself still exists.
      expect(fs.existsSync(path.join(spoke, ".claude", ".agentboot-manifest.json"))).toBe(true);
    } finally {
      fs.rmSync(hub, { recursive: true, force: true });
      fs.rmSync(spoke, { recursive: true, force: true });
    }
  });

  it("envelope declares its signature format honestly (sshsig, not sigstore)", () => {
    const manifest: Record<string, unknown> = { files: [], provenance: {}, scope: null, synced_at: null };
    manifest["integrity"] = { algorithm: "sha256", manifest_digest: computeManifestDigest(manifest) };
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ab-att-key-"));
    try {
      const key = path.join(dir, "k");
      execSync(`ssh-keygen -q -t ed25519 -N "" -f "${key}"`, { timeout: 15_000 });
      const out = buildDsseEnvelope(manifest, key);
      expect("envelope" in out).toBe(true);
      if ("envelope" in out) {
        expect(out.envelope.payloadType).toBe(INTOTO_PAYLOAD_TYPE);
        expect(out.envelope.x_agentboot.signature_format).toBe("sshsig");
        expect(out.envelope.x_agentboot.note).toContain("Not a Sigstore bundle");
      }
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("AGENTS.md import discovery", () => {
  it("finds root AND nested AGENTS.md, skips vendored trees, classifies as agents-md", () => {
    const repo = fs.mkdtempSync(path.join(os.tmpdir(), "ab-agentsmd-"));
    try {
      fs.writeFileSync(path.join(repo, "AGENTS.md"), "# root instructions\nUse tabs.\n");
      fs.mkdirSync(path.join(repo, "packages", "api"), { recursive: true });
      fs.writeFileSync(path.join(repo, "packages", "api", "AGENTS.md"), "# api instructions\nUse zod.\n");
      fs.mkdirSync(path.join(repo, "node_modules", "dep"), { recursive: true });
      fs.writeFileSync(path.join(repo, "node_modules", "dep", "AGENTS.md"), "# vendored — must be skipped\n");

      const manifest = scanRepoDirs([repo]);
      const agentsFiles = manifest.files.filter((f) => f.type === "agents-md");
      const rels = agentsFiles.map((f) => f.relativePath.replace(/\\/g, "/")).sort();
      expect(rels).toEqual(["AGENTS.md", "packages/api/AGENTS.md"]);
    } finally {
      fs.rmSync(repo, { recursive: true, force: true });
    }
  });
});
